### ISSUE TITLE
Edge Version

### ISSUE THREAD

**Issue by csharpfritz** [clarkio/azure-mask#39]
It would be great if we could use this in Edge

**Comment by mark-szabo** [comment]
Now you can use Chrome extensions in the new Chromium-based Edge 😉

**Comment by FBoucher** [comment]
FYI 
It is totally possible. Download the Zip file from the Realese. UnZip it somewhere and import a unpack expansion ...

**Comment by taqabubaker** [comment]
> It would be awesome if it can be put in the Edge Store https://microsoftedge.microsoft.com/insider-addons/category/EdgeExtensions

I found the extension in the Edge Store (check the screenshot). It seems someone called Money Yu uploaded it there.
I'm not sure how future releases can be uploaded since the extension in the store not owned by @clarkio 🤷🏻‍♂️

![image](https://user-images.githubusercontent.com/17325563/91925661-26702500-ecde-11ea-9c66-64b48fd15b70.png)

**Comment by lettucebo** [comment]
Hi I'm the uploader

I upload this package is because I really tired to use folder loading the development package

I'm happy to update the package once have update or transfer the ownership to @mark-szabo for continues maintain

**Comment by mark-szabo** [comment]
@lettucebo 
> I'm happy to update the package once have update or transfer the ownership to @mark-szabo for continues maintain

The creator of this is @clarkio and not myself. 🙂

**Comment by clarkio** [comment]
I appreciate the earnestness of adding the extension to the Edge Store but hope it doesn't get confusing to others. If folks would prefer it in the Edge Store I can take some time to publish it myself. Let me know what you all would prefer.

I know it looks as though the extension is stagnant now but it has been driving some conversations (offline) around more practical solutions to the problem the extension is trying to solve. Because of that I've held off from spending time on it and addressing gaps identified by the community.

**Comment by clarkio** [comment]
@lettucebo I've began more maintenance on the extension again. You can transfer ownership to me or take it down.

Also question for everyone here: Do you all feel it's necessary to have another instance of the extension in the Edge Add-Ons store still? The Chrome Web Store is accessible in Edge which is how I would think most folks would install, right? (once it's approved and available there again of course)

**Comment by csharpfritz** [comment]
Now that Edge uses the Chrome add-ins, I agree -- no need for an
Edge-specific feature

**Comment by lettucebo** [comment]
@clarkio I try to find the option to let me transfer the ownership but can't find where it is

Can you share some light that how I transfer the ownership?

**Comment by clarkio** [comment]
Hmm I'm not sure @lettucebo but thinking about it more, since there isn't a need to have a separate instance of this published to just the Edge marketplace (due to access to the Chrome one) could you remove the one you've published?

**Comment by lettucebo** [comment]
@clarkio I had remove the extension from the store.

**Comment by clarkio** [comment]
Ok thank you! Closing this issue now

**Comment by taqabubaker** [comment]
@clarkio it seems the extension not yet approved by Google because I can't find it in their extension store 😞
Any idea when Google will approve the extension?

**Comment by clarkio** [comment]
@taqabubaker I'm waiting on an update email from the folks that caused the take down of the extension. Hoping to see some progress on that this week.
