### ISSUE TITLE
The Bot Framework MicrosoftAppPassword is not masked at all

### ISSUE THREAD

**Issue by peterblazejewicz** [clarkio/azure-mask#43]
The extensions masks `MicrosoftAppId` key, but the more important `MicrosoftAppPassword` seems to be not maked at all:

![image](https://user-images.githubusercontent.com/14539/39649244-7989d22e-4fe5-11e8-81e0-b4ebba3f7e2e.png)

Thanks!

**Comment by peterblazejewicz** [comment]
Hm, looking into the DOM markup it looks like an issue (a bug) with the Azure portal itself, the row in the KO table is missing `azdev-sensitive` class this extension is using as selector.

**Comment by clarkio** [comment]
Hey thanks for taking the time to report this. I'm finally getting back into working on this a bit more lately. 

I checked into this area of the portal and it looks like it is now natively hiding these fields until you click on them. Being that this is the case I believe there isn't a need for this extension to mask the fields any more than they are now.

Let me know if you agree (closing unless you request otherwise)
